package gcp

type Labels struct {
	InstanceID string `json:"instance_id"`
	ProjectID  string `json:"project_id"`
	Zone       string `json:"zone"`
}
type Resource struct {
	Type   string `json:"type"`
	Labels Labels `json:"labels"`
}

type MetricLabels struct {
	InstanceName string `json:"instance_name"`
}

type Metric struct {
	Type        string       `json:"type"`
	DisplayName string       `json:"displayName"`
	Labels      MetricLabels `json:"labels"`
}

type SystemLabels struct {
	Labelkey string `json:"labelkey"`
}

type UserLabels struct {
	Labelkey string `json:"labelkey"`
}
type Metadata struct {
	SystemLabels SystemLabels `json:"system_labels"`
	UserLabels   UserLabels   `json:"user_labels"`
}
type PolicyUserLabels struct {
	UserLabel1 string `json:"user-label-1"`
	UserLabel2 string `json:"user-label-2"`
}
type Aggregation struct {
	AlignmentPeriod  string `json:"alignmentPeriod"`
	PerSeriesAligner string `json:"perSeriesAligner"`
}
type Trigger struct {
	Count int `json:"count"`
}
type ConditionThreshold struct {
	Filter         string        `json:"filter"`
	Aggregations   []Aggregation `json:"aggregations"`
	Comparison     string        `json:"comparison"`
	ThresholdValue float64       `json:"thresholdValue"`
	Duration       string        `json:"duration"`
	Trigger        Trigger       `json:"trigger"`
}

type Condition struct {
	Name               string             `json:"name"`
	DisplayName        string             `json:"displayName"`
	ConditionThreshold ConditionThreshold `json:"conditionThreshold"`
}

type Documentation struct {
	Content  string `json:"content"`
	MimeType string `json:"mime_type"`
}
type Incident struct {
	IncidentID              string           `json:"incident_id"`
	ScopingProjectID        string           `json:"scoping_project_id"`
	ScopingProjectNumber    int              `json:"scoping_project_number"`
	URL                     string           `json:"url"`
	StartedAt               int              `json:"started_at"`
	EndedAt                 int              `json:"ended_at"`
	State                   string           `json:"state"`
	ResourceID              string           `json:"resource_id"`
	ResourceName            string           `json:"resource_name"`
	ResourceDisplayName     string           `json:"resource_display_name"`
	ResourceTypeDisplayName string           `json:"resource_type_display_name"`
	Resource                Resource         `json:"resource"`
	Metric                  Metric           `json:"metric"`
	Metadata                Metadata         `json:"metadata"`
	PolicyName              string           `json:"policy_name"`
	PolicyUserLabels        PolicyUserLabels `json:"policy_user_labels"`
	ConditionName           string           `json:"condition_name"`
	ThresholdValue          string           `json:"threshold_value"`
	ObservedValue           string           `json:"observed_value"`
	Condition               Condition        `json:"condition"`
	Documentation           Documentation    `json:"documentation"`
	Summary                 string           `json:"summary"`
}
type AutoGenerated struct {
	Incident Incident `json:"incident"`
	Version  string   `json:"version"`
}
